[[GMT]]
arch = "aarch64"
git-tree-sha1 = "23fe09df89c2656f229bd9c76c41cfb45d1109e6"
os = "macos"

    [[GMT.download]]
    sha256 = "d7fd4603e4fd4e5f4254daaf9410f84c1401fc5e298df9cc076f02522f7686ab"
    url = "https://github.com/JuliaBinaryWrappers/GMT_jll.jl/releases/download/GMT-v6.7.0+0/GMT.v6.7.0.aarch64-apple-darwin.tar.gz"
[[GMT]]
arch = "aarch64"
git-tree-sha1 = "215fd53d87a29faace239e3463c644b7673be4f5"
libc = "glibc"
os = "linux"

    [[GMT.download]]
    sha256 = "41ca8f7caa5da14bb7733d9953c74357933cc5266b1c6442c81ae76c9fb50e0c"
    url = "https://github.com/JuliaBinaryWrappers/GMT_jll.jl/releases/download/GMT-v6.7.0+0/GMT.v6.7.0.aarch64-linux-gnu.tar.gz"
[[GMT]]
arch = "i686"
git-tree-sha1 = "f5b065fe8d9e06dfd0684cf27fab1bdc0ea1021a"
os = "windows"

    [[GMT.download]]
    sha256 = "d7494533126127dfcbd976c4f4261cec574d008d16dcc15651a5f01a8d00ac26"
    url = "https://github.com/JuliaBinaryWrappers/GMT_jll.jl/releases/download/GMT-v6.7.0+0/GMT.v6.7.0.i686-w64-mingw32.tar.gz"
[[GMT]]
arch = "x86_64"
git-tree-sha1 = "b0e494794a6b9c65b8cc61f0d7ebefbd7f4d3b90"
os = "macos"

    [[GMT.download]]
    sha256 = "389ec82fd12e72b06e0026c7897ace6c9ad8bed8b745b259e739771cf9a07f1e"
    url = "https://github.com/JuliaBinaryWrappers/GMT_jll.jl/releases/download/GMT-v6.7.0+0/GMT.v6.7.0.x86_64-apple-darwin.tar.gz"
[[GMT]]
arch = "x86_64"
git-tree-sha1 = "dfb00a9778fc26c107653b5e57168eba6203243b"
libc = "glibc"
os = "linux"

    [[GMT.download]]
    sha256 = "a49f0e01d3982c259442a8a08e1acc193db13b94120a7c0a38c69033d3f74864"
    url = "https://github.com/JuliaBinaryWrappers/GMT_jll.jl/releases/download/GMT-v6.7.0+0/GMT.v6.7.0.x86_64-linux-gnu.tar.gz"
[[GMT]]
arch = "x86_64"
git-tree-sha1 = "2601bdebecc4a3077cb6a68e31eb56f9dc84b072"
os = "windows"

    [[GMT.download]]
    sha256 = "61df9c683a97438cdcbd3614a4acfffbced872dd7daa87ea82a20e6ed80def08"
    url = "https://github.com/JuliaBinaryWrappers/GMT_jll.jl/releases/download/GMT-v6.7.0+0/GMT.v6.7.0.x86_64-w64-mingw32.tar.gz"
